export enum ErrorMessage {
    UserRequired = 'User is required',
    TitleRequired = 'Title is required',
    DescriptionRequired = 'Description is required',
    LessonStartRequired = 'Lesson start is required',
    LessonEndRequired = 'Lesson end is required',
    LessonEndAfterStart = 'Lesson end must be after its start',
    LessonExistsAtThisTime = 'There is an existing lesson at this time',
    InvalidRecurrenceInput = 'Invalid recurrence',
    RecurrenceDaysRequired = 'Recurrence days are required',
    RecurrenceEndRequired = 'Recurrence end is required',
    EndDateAfterStartDate = 'Recurrence end must be after end date',
    DurationRequired = 'Duration is required',
    LessonRequired = 'Lesson is required',
    LessonNotExist = 'Lesson does not exist',
    OldDateRequired = 'Old date is required',
    NewDateRequired = 'New date is required',
    StartDateRequired = 'Start date is required',
    EndDateRequired = 'End date is required',
    LessonNotAtThisDate = 'The lesson does not occur at this time',
}
